version: '3'

services:
  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx
    container_name: sfinoe_nginx
    volumes:
      - /home/zkasmi/data:/var/www
    ports:
      - 443:443
    networks:
      - Linker
    restart: on-failure
  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    container_name: sfinoe_wordpress
    volumes:
      - /home/zkasmi/data:/var/www
    restart: on-failure
    ports:
      - 9000:9000
    env_file:
      - .env
    networks:
      - Linker
  mariadb:
    build: ./requirements/mariadb
    container_name: sfinoe_mariadb
    volumes:
      - /home/zkasmi/data:/var/lib/mysql
    restart: on-failure
    ports:
      - 3306:3306
    env_file:
      - .env
    networks:
      - Linker
networks:
  Linker:
