version: "3"

services:
  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx
    container_name: nginx
    volumes:
      - wp:/var/www/html
    ports:
      - 443:443
    networks:
      - sfinoe_net
    restart: on-failure

  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - wp:/var/www/html
    restart: on-failure
    env_file:
      - .env
    networks:
      - sfinoe_net

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - db:/var/lib/mysql
    restart: on-failure
    env_file:
      - .env
    networks:
      - sfinoe_net

networks:
  sfinoe_net:
    name: sfinoe_net
    driver: bridge # Host, none, bridge, overlay

volumes:
  wp:
    driver: local # local, nfs, s3
    name: wp
    driver_opts:
      type: none # none, nfs, s3
      o: bind # bind, uid, gid, mode
      device: /home/sfinoe/data/wordpress
  db:
    driver: local
    name: db
    driver_opts:
      type: none
      o: bind
      device: /home/sfinoe/data/mariadb
