CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'test'@'%' IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES ON wordpress.* TO 'test'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY '123456';
